# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemos < Formula
  desc "Persistent memory and skills for AI coding agents. MCP-native, single binary, zero deps."
  homepage "https://github.com/polyxmedia/mnemos"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/polyxmedia/mnemos/releases/download/v0.10.0/mnemos_0.10.0_Darwin_x86_64.tar.gz"
      sha256 "1104d8715eed22aac1c04680e3ef08b9840b4381e1b61e2c922f5e5f9192ca51"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/polyxmedia/mnemos/releases/download/v0.10.0/mnemos_0.10.0_Darwin_arm64.tar.gz"
      sha256 "f43f13643e72d2e1dd2e496643bd053c12283f33b500636c3cda9f4a0099e4eb"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/polyxmedia/mnemos/releases/download/v0.10.0/mnemos_0.10.0_Linux_x86_64.tar.gz"
      sha256 "dd6287626c3b12da75bf9aef770f0222ae083c1a7ece37580c28e78f19c095c0"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/polyxmedia/mnemos/releases/download/v0.10.0/mnemos_0.10.0_Linux_arm64.tar.gz"
      sha256 "1855460ef1679e786028c4f7505e11e0d4203cbec2645ac43aa1142ca0ca3341"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  test do
    system "#{bin}/mnemos version"
  end
end
